#!/bin/bash
#SBATCH --time=1-00:00:00
#SBATCH --output=/om/user/chengxuz/slurm_out_all/barrel_hdf5_%j.out

source activate env_torch
#python cmd_hdf5.py --pathhdf5 /om/user/chengxuz/barrel/hdf5s_new_name --pathexe /om/user/chengxuz/barrel/example_build/Constraints/App_TestHinge --fromcfg /om/user/chengxuz/barrel/barrel/cmd_gen_mp4/opt_results/para_ --pathconfig /om/user/chengxuz/barrel/configs --objindx ${1} --pindxlen 36 --scindxlen 6 --oindxsta ${2} --spindxsta ${3} --generatemode 2 --testmode 2
#python cmd_hdf5.py --pathhdf5 /om/user/chengxuz/barrel/hdf5s_new_name_fix --pathexe /om/user/chengxuz/barrel/example_build/Constraints/App_TestHinge --fromcfg /om/user/chengxuz/barrel/barrel/cmd_gen_mp4/opt_results/para_ --pathconfig /om/user/chengxuz/barrel/configs --objindx ${1} --pindxsta ${2} --scindxsta ${3} --oindxsta ${4} --oindxlen 3 --spindxlen 14 --generatemode 2 --testmode 2
#python cmd_hdf5.py --pathhdf5 /om/user/chengxuz/barrel/testdataset_dis --pathexe /om/user/chengxuz/barrel/example_build/Constraints/App_TestHinge --fromcfg /om/user/chengxuz/barrel/barrel/cmd_gen_mp4/opt_results/para_ --pathconfig /om/user/chengxuz/barrel/configs --objindx ${1} --pindxsta ${2} --scindxsta ${3} --oindxsta ${4} --oindxlen 5 --spindxlen 14 --generatemode 2 --testmode 2 --pindxlen 3
#python cmd_hdf5.py --pathhdf5 /om/user/chengxuz/barrel/testdataset_dis --pathexe /om/user/chengxuz/barrel/example_build/Constraints/App_TestHinge --fromcfg /om/user/chengxuz/barrel/barrel/cmd_gen_mp4/opt_results/para_ --pathconfig /om/user/chengxuz/barrel/configs --objindx ${1} --pindxsta ${2} --scindxsta ${3} --spindxsta ${4} --oindxsta ${5} --generatemode 2 --testmode 2
python cmd_hdf5.py --pathhdf5 /om/user/chengxuz/barrel/testdataset_control${5} --pathexe /om/user/chengxuz/barrel/example_build/Constraints/App_TestHinge --fromcfg /om/user/chengxuz/barrel/barrel/cmd_gen_mp4/opt_results/para_ --pathconfig /om/user/chengxuz/barrel/configs --objindx ${1} --generatemode 3 --testmode 2 --smallolen 1 --smallplen 1 --bigsamnum ${2} --hdf5suff ${3} --randseed ${4} --checkmode 1 --whichcontrol ${5}
#python cmd_hdf5.py --pathhdf5 /om/user/chengxuz/barrel/testdataset_control${5} --pathexe /om/user/chengxuz/barrel/example_build/Constraints/App_TestHinge --fromcfg /om/user/chengxuz/barrel/barrel/cmd_gen_mp4/opt_results/para_ --pathconfig /om/user/chengxuz/barrel/configs --objindx ${1} --generatemode 3 --testmode 2 --smallolen 1 --smallplen 1 --bigsamnum ${2} --hdf5suff ${3} --randseed ${4} --checkmode 1 --whichcontrol ${5} --whichbig ${6}
